name: Docker Build & Deploy to EKS

on:
  push:
    branches:
      - main
    paths:
      - "docker/**"
      - "kubernetes/**"
  workflow_run:
    workflows: ["Terraform Infra"]
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # -------------------------
      # CHECKOUT CODE
      # -------------------------
      - name: Checkout repository
        uses: actions/checkout@v4

      # -------------------------
      # AWS AUTHENTICATION
      # -------------------------
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # -------------------------
      # DOCKER BUILD & PUSH TO ECR
      # -------------------------
      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-1 \
          | docker login --username AWS --password-stdin 859012632884.dkr.ecr.us-east-1.amazonaws.com

      - name: Build Docker image
        working-directory: docker
        run: docker build -t hello-app .

      - name: Tag Docker image with Git SHA
        run: |
          IMAGE_TAG=${GITHUB_SHA::7}  # first 7 characters of commit SHA
          docker tag hello-app:latest 859012632884.dkr.ecr.us-east-1.amazonaws.com/hrgf-image-repo:$IMAGE_TAG
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Push Docker image to ECR
        run: |
          docker push 859012632884.dkr.ecr.us-east-1.amazonaws.com/hrgf-image-repo:$IMAGE_TAG

      # -------------------------
      # DEPLOY TO EKS
      # -------------------------
      - name: Update kubeconfig for EKS cluster
        run: |
          aws eks update-kubeconfig --region us-east-1 --name HRGF-project-cluster-2

      - name: Deploy application to Kubernetes
        run: |
          # Replace image in deployment.yaml dynamically with new image tag
          sed -i "s|image: .*|image: 859012632884.dkr.ecr.us-east-1.amazonaws.com/hrgf-image-repo:$IMAGE_TAG|" kubernetes/deployment.yaml

          # Apply deployment and service manifests (will create if not exist)
          kubectl apply -f kubernetes/deployment.yaml
          kubectl apply -f kubernetes/service.yaml

          # Wait for deployment rollout to complete
          kubectl rollout status deployment/hello-app

