name: Build & Deploy Hello-App to EKS

on:
  push:
    branches:
      - main
    paths:
      - "docker/**"
      - "kubernetes/**"
  workflow_dispatch:
  workflow_run:
    workflows: ["Terraform Infra"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # -------------------------
      # 1. Checkout code
      # -------------------------
      - name: Checkout repository
        uses: actions/checkout@v4

      # -------------------------
      # 2. Configure AWS credentials
      # -------------------------
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # -------------------------
      # 3. Build and push Docker image to ECR
      # -------------------------
      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-1 \
          | docker login --username AWS --password-stdin 859012632884.dkr.ecr.us-east-1.amazonaws.com

      - name: Build Docker image
        working-directory: docker
        run: docker build -t hello-app .

      - name: Tag Docker image as latest
        run: docker tag hello-app:latest 859012632884.dkr.ecr.us-east-1.amazonaws.com/hello-app-repo:latest

      - name: Push Docker image to ECR
        run: docker push 859012632884.dkr.ecr.us-east-1.amazonaws.com/hello-app-repo:latest

      # -------------------------
      # 4. Configure kubectl for EKS
      # -------------------------
      - name: Update kubeconfig for EKS cluster
        run: aws eks update-kubeconfig --region us-east-1 --name HRGF-project-cluster-2

      # -------------------------
      # 5. Deploy to Kubernetes
      # -------------------------
      - name: Apply Kubernetes manifests
        run: |
          # Apply Deployment and Service YAMLs
          kubectl apply -f kubernetes/deployment.yaml
          kubectl apply -f kubernetes/service.yaml

          # Wait for deployment rollout to complete
          kubectl rollout status deployment/hello-app

      # -------------------------
      # 6. Show service details
      # -------------------------
      - name: Get LoadBalancer details
        run: kubectl get svc hello-app-service -o wide

